PlaneApp/config/routes.rb
Rails.application.routes.draw do
  resources :planeflights

  resources :planes

end

PlaneApp/app/models/plane.rb
class Plane < ActiveRecord::Base
end

PlaneApp/app/models/planeflight.rb
class Planeflight < ActiveRecord::Base
  belongs_to :plane
end

PlaneApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

PlaneApp/app/controllers/planeflights_controller.rb
class PlaneflightsController < ApplicationController
  before_action :set_planeflight, only: [:show, :edit, :update, :destroy]

  # GET /planeflights
  # GET /planeflights.json
  def index
    @planeflights = Planeflight.all
  end

  # GET /planeflights/1
  # GET /planeflights/1.json
  def show
  end

  # GET /planeflights/new
  def new
    @planeflight = Planeflight.new
  end

  # GET /planeflights/1/edit
  def edit
  end

  # POST /planeflights
  # POST /planeflights.json
  def create
    @planeflight = Planeflight.new(planeflight_params)

    respond_to do |format|
      if @planeflight.save
        format.html { redirect_to @planeflight, notice: 'Planeflight was successfully created.' }
        format.json { render :show, status: :created, location: @planeflight }
      else
        format.html { render :new }
        format.json { render json: @planeflight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /planeflights/1
  # PATCH/PUT /planeflights/1.json
  def update
    respond_to do |format|
      if @planeflight.update(planeflight_params)
        format.html { redirect_to @planeflight, notice: 'Planeflight was successfully updated.' }
        format.json { render :show, status: :ok, location: @planeflight }
      else
        format.html { render :edit }
        format.json { render json: @planeflight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /planeflights/1
  # DELETE /planeflights/1.json
  def destroy
    @planeflight.destroy
    respond_to do |format|
      format.html { redirect_to planeflights_url, notice: 'Planeflight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_planeflight
      @planeflight = Planeflight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def planeflight_params
      params.require(:planeflight).permit(:plane_id, :airline, :number, :fromcity, :tocity)
    end
end

PlaneApp/app/controllers/planes_controller.rb
class PlanesController < ApplicationController
  before_action :set_plane, only: [:show, :edit, :update, :destroy]

  # GET /planes
  # GET /planes.json
  def index
    @planes = Plane.all
  end

  # GET /planes/1
  # GET /planes/1.json
  def show
  end

  # GET /planes/new
  def new
    @plane = Plane.new
  end

  # GET /planes/1/edit
  def edit
  end

  # POST /planes
  # POST /planes.json
  def create
    @plane = Plane.new(plane_params)

    respond_to do |format|
      if @plane.save
        format.html { redirect_to @plane, notice: 'Plane was successfully created.' }
        format.json { render :show, status: :created, location: @plane }
      else
        format.html { render :new }
        format.json { render json: @plane.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /planes/1
  # PATCH/PUT /planes/1.json
  def update
    respond_to do |format|
      if @plane.update(plane_params)
        format.html { redirect_to @plane, notice: 'Plane was successfully updated.' }
        format.json { render :show, status: :ok, location: @plane }
      else
        format.html { render :edit }
        format.json { render json: @plane.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /planes/1
  # DELETE /planes/1.json
  def destroy
    @plane.destroy
    respond_to do |format|
      format.html { redirect_to planes_url, notice: 'Plane was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plane
      @plane = Plane.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plane_params
      params.require(:plane).permit(:manufacturer, :model, :seats)
    end
end

PlaneApp/app/helpers/application_helper.rb
module ApplicationHelper
end

PlaneApp/app/helpers/planeflights_helper.rb
module PlaneflightsHelper
end

PlaneApp/app/helpers/planes_helper.rb
module PlanesHelper
end

PlaneApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PlaneApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

PlaneApp/app/views/planeflights/_form.html.erb
<%= form_for(@planeflight) do |f| %>
  <% if @planeflight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@planeflight.errors.count, "error") %> prohibited this planeflight from being saved:</h2>

      <ul>
      <% @planeflight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :plane_id %><br>
    <%= f.text_field :plane_id %>
  </div>
  <div class="field">
    <%= f.label :airline %><br>
    <%= f.text_field :airline %>
  </div>
  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :fromcity %><br>
    <%= f.text_field :fromcity %>
  </div>
  <div class="field">
    <%= f.label :tocity %><br>
    <%= f.text_field :tocity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

PlaneApp/app/views/planeflights/edit.html.erb
<h1>Editing planeflight</h1>

<%= render 'form' %>

<%= link_to 'Show', @planeflight %> |
<%= link_to 'Back', planeflights_path %>

PlaneApp/app/views/planeflights/index.html.erb
<h1>Listing planeflights</h1>

<table>
  <thead>
    <tr>
      <th>Plane</th>
      <th>Airline</th>
      <th>Number</th>
      <th>Fromcity</th>
      <th>Tocity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @planeflights.each do |planeflight| %>
      <tr>
        <td><%= planeflight.plane %></td>
        <td><%= planeflight.airline %></td>
        <td><%= planeflight.number %></td>
        <td><%= planeflight.fromcity %></td>
        <td><%= planeflight.tocity %></td>
        <td><%= link_to 'Show', planeflight %></td>
        <td><%= link_to 'Edit', edit_planeflight_path(planeflight) %></td>
        <td><%= link_to 'Destroy', planeflight, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Planeflight', new_planeflight_path %>

PlaneApp/app/views/planeflights/new.html.erb
<h1>New planeflight</h1>

<%= render 'form' %>

<%= link_to 'Back', planeflights_path %>

PlaneApp/app/views/planeflights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Plane:</strong>
  <%= @planeflight.plane %>
</p>

<p>
  <strong>Airline:</strong>
  <%= @planeflight.airline %>
</p>

<p>
  <strong>Number:</strong>
  <%= @planeflight.number %>
</p>

<p>
  <strong>Fromcity:</strong>
  <%= @planeflight.fromcity %>
</p>

<p>
  <strong>Tocity:</strong>
  <%= @planeflight.tocity %>
</p>

<%= link_to 'Edit', edit_planeflight_path(@planeflight) %> |
<%= link_to 'Back', planeflights_path %>

PlaneApp/app/views/planes/_form.html.erb
<%= form_for(@plane) do |f| %>
  <% if @plane.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plane.errors.count, "error") %> prohibited this plane from being saved:</h2>

      <ul>
      <% @plane.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :manufacturer %><br>
    <%= f.text_field :manufacturer %>
  </div>
  <div class="field">
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :seats %><br>
    <%= f.number_field :seats %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

PlaneApp/app/views/planes/edit.html.erb
<h1>Editing plane</h1>

<%= render 'form' %>

<%= link_to 'Show', @plane %> |
<%= link_to 'Back', planes_path %>

PlaneApp/app/views/planes/index.html.erb
<h1>Listing planes</h1>

<table>
  <thead>
    <tr>
      <th>Manufacturer</th>
      <th>Model</th>
      <th>Seats</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @planes.each do |plane| %>
      <tr>
        <td><%= plane.manufacturer %></td>
        <td><%= plane.model %></td>
        <td><%= plane.seats %></td>
        <td><%= link_to 'Show', plane %></td>
        <td><%= link_to 'Edit', edit_plane_path(plane) %></td>
        <td><%= link_to 'Destroy', plane, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Plane', new_plane_path %>

PlaneApp/app/views/planes/new.html.erb
<h1>New plane</h1>

<%= render 'form' %>

<%= link_to 'Back', planes_path %>

PlaneApp/app/views/planes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Manufacturer:</strong>
  <%= @plane.manufacturer %>
</p>

<p>
  <strong>Model:</strong>
  <%= @plane.model %>
</p>

<p>
  <strong>Seats:</strong>
  <%= @plane.seats %>
</p>

<%= link_to 'Edit', edit_plane_path(@plane) %> |
<%= link_to 'Back', planes_path %>